name: ci-docker-publish-github
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set date tag
        id: set_date_tag
        run: |
          echo "date_tag=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Set variables
        id: set_vars
        run: |
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "created=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
          echo "platforms=linux/amd64,linux/386,linux/arm64,linux/arm/v6,linux/arm/v7" >> $GITHUB_OUTPUT

      - name: Build and push to GitHub Container Registry with date tag
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ steps.set_vars.outputs.platforms }}
          build-args: |
            CREATED=${{ steps.set_vars.outputs.created }}
            COMMIT=${{ steps.set_vars.outputs.commit }}
            VERSION=${{ steps.set_date_tag.outputs.date_tag }}
          tags: |
            ghcr.io/${{ github.repository | lower }}:${{ steps.set_date_tag.outputs.date_tag }}
          push: true

      - name: Build and push to GitHub Container Registry with latest tag
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ steps.set_vars.outputs.platforms }}
          build-args: |
            CREATED=${{ steps.set_vars.outputs.created }}
            COMMIT=${{ steps.set_vars.outputs.commit }}
            VERSION=latest
          tags: |
            ghcr.io/${{ github.repository | lower }}:latest
          push: true

      - name: Clean up artifacts
        run: |
          # Clean up Docker build cache
          docker system prune -f
          # Clean up workspace
          rm -rf ${{ github.workspace }}/node_modules
          rm -rf ${{ github.workspace }}/.npm
