name: ci-docker-publish-aliyun
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      REGISTRY: registry.cn-shenzhen.aliyuncs.com
      IMAGE_NAME: store2024/2fa
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Set date tag
        id: set_date_tag
        run: |
          echo "date_tag=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Set variables
        id: set_vars
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: |
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "created=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
          echo "platforms=linux/amd64,linux/386" >> $GITHUB_OUTPUT

      - name: Build and push to Aliyun Container Registry with date tag
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ steps.set_vars.outputs.platforms }}
          build-args: |
            CREATED=${{ steps.set_vars.outputs.created }}
            COMMIT=${{ steps.set_vars.outputs.commit }}
            VERSION=${{ steps.set_date_tag.outputs.date_tag }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.set_date_tag.outputs.date_tag }}
          push: true

      - name: Build and push to Aliyun Container Registry with latest tag
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ steps.set_vars.outputs.platforms }}
          build-args: |
            CREATED=${{ steps.set_vars.outputs.created }}
            COMMIT=${{ steps.set_vars.outputs.commit }}
            VERSION=latest
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          push: true

  delete-artifacts:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: "*"
          failOnError: false
